#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#


image:
  repository: linuxserver/ombi
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100
service:
  main:
    enabled: true
    type: ClusterIP
    
  ports:
    http:
      enabled: true
      port: 3579 
      targetPort: 3579 
      protocol: HTTP

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels: {}
    ingressClassName:  traefik # "nginx"
    hosts:
      - host: ombi.gygax.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              name: ombi
              port: 3579 

persistence:
  config:
    enabled: true
    type: pvc
    mountPath:  /config # /config
    readOnly: false
    nameOverride: config
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true

metrics:
  enabled: false
  serviceMonitor:
    interval: 3m
    scrapeTimeout: 1m
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []
  exporter:
    image:
      repository: ghcr.io/onedr0p/exportarr
      tag: v1.3.1
      pullPolicy: IfNotPresent
    env:
      port: 9793
      additionalMetrics: false
      unknownQueueItems: false
