
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100

service:
  main:
    enabled: true
    type: ClusterIP
    
  ports:
    http:
      enabled: true
      port: 8096
      targetPort: 8096
      protocol: HTTP

ingress:
  enabled: true
  primary: true
  nameOverride:
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  customRequestHeaders:
    X-Robots-Tag: noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex
    STSSeconds: 315360000
    STSIncludeSubdomains: true
    STSPreload: true
    forceSTSHeader: true
    frameDeny: true
    contentTypeNosniff: true
    customFrameOptionsValue: allow-from https://jellyfin.gygax.cloud
  customresponseheaders:
    X-XSS-PROTECTION: 1


  labels: {}
  ingressClassName:  traefik # "nginx"
  hosts:
  - host: jellyfin.gygax.cloud
    paths:
      - path: /
        pathType: Prefix
        service:
          name: jellyfin
          port: 8096

persistence:
  config:
    enabled: true
    type: pvc
    mountPath:  /config # /config
    readOnly: false
    nameOverride: config
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false

  media:
    enabled: true
    type: pvc
    mountPath:  /media # /config
    readOnly: false
    nameOverride: media
    storageClass: # "-"
    existingClaim: media-pvc # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 5Ti
    retain: true

metrics:
  enabled: false
  serviceMonitor:
    interval: 3m
    scrapeTimeout: 1m
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []
  exporter:
    image:
      repository: ghcr.io/onedr0p/exportarr
      tag: v1.3.1
      pullPolicy: IfNotPresent
    env:
      port: 9793
      additionalMetrics: false
      unknownQueueItems: false
