
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 8096
        enabled: true
        targetPort: 8096
        protocol: HTTP

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels: {}
    ingressClassName:  traefik # "nginx"

    headers: 
      customRequestHeaders:
        Connection: keep-alive, Upgrade
        Upgrade: WebSocket
        X-Robots-Tag: noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex
        STSSeconds: 315360000
        STSIncludeSubdomains: true
        STSPreload: true
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        customFrameOptionsValue: allow-from https://jellyfin.gygax.cloud
      customresponseheaders:
        X-XSS-PROTECTION: 1

    hosts:
    - host: jellyfin.gygax.cloud
      paths:
      - path: /
        pathType: Prefix
        service:
          name: jellyfin
          port: 8096

persistence:



  data:
    enabled: true
    type: pvc
    mountPath:  /data # /config
    readOnly: false
    nameOverride: data
    storageClass: # "-"
    existingClaim: media-pvc # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 5Ti
    retain: true

  cache:
    enabled: true
    type: pvc
    mountPath:  /cache # /config
    readOnly: false
    nameOverride: cache
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false

  metadata:
    enabled: true
    type: pvc
    mountPath:  /metadata # /config
    readOnly: false
    nameOverride: metadata
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: false

  config:
    enabled: true
    type: pvc
    mountPath:  /config # /config
    readOnly: false
    nameOverride: config
    storageClass:  longhorn # "-"
    existingClaim:  # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true