# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#
defaultPodOptions:
  automountServiceAccountToken: true

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    containers:
      ombi:
        image:
          repository: linuxserver/ombi
          pullPolicy: IfNotPresent
          tag: latest
        # We don't change the user as this won't work otherwise.
        # securityContext:
        #   runAsUser: 1033
        #   runAsGroup: 100

        env:
          TZ: Europe/Zurich
service:
  main:
    controller: main
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 3579

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    className: traefik # "nginx"
    hosts:
      - host: ombi.gygax.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 3579

persistence:
  config:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      main:
        ombi:
          - path: /config
