#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
# helm install stash k8s-at-home/stash -f stash/values.yml

image:
  repository: stashapp/stash
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100

service:
  main:
    enabled: true
    type: ClusterIP
    
  ports:
    http:
      enabled: true
      port: 9999
      targetPort: 9999
      protocol: HTTP

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels: {}
    ingressClassName:  traefik # "nginx"
    hosts:
      - host: stash.gygax.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              name: stash
              port: 9999

persistence:
  data:
    enabled: true
    type: pvc
    mountPath:  /data # /config
    readOnly: false
    nameOverride: data
    storageClass: # "-"
    existingClaim: nsfw-pvc # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 1Ti
    retain: true
  
  config:
    enabled: true
    type: pvc
    mountPath:  /root/.stash # /config
    readOnly: false
    nameOverride: config
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
