
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-credentials
#   namespace: traefik
# type: Opaque
# stringData:
#   email: <email>
#   api-token: <api-token>
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: traefik
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fabian@gygax.tech
    privateKeySecretRef:
      name: gygax-cloud-wildcard-pk
    solvers:
      - dns01:
          cloudflare:
            email: fabian@gygax.tech
            apiTokenSecretRef:
              name: cloudflare-api-credentials
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gygax-cloud-cert
  namespace: traefik
spec:
  secretName: gygax-cloud-wildcard-cert-data
  dnsNames:
    - "*.gygax.cloud"
  issuerRef:
    name: cloudflare
    kind: Issuer
