---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: azuredns
  namespace: traefik
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fabian@gygax.tech
    privateKeySecretRef:
      name: gygax-cloud-wildcard-pk-azure
    solvers:
      - dns01:
          azureDNS:
            clientID: 301cd847-3140-456e-a205-c5e591e529b9
            clientSecretSecretRef:
              # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
              name: azuredns-config
              key: client-secret
            subscriptionID: 01086eaa-80d0-42d1-84a3-23563f1a6691
            tenantID: cf3ccd07-66cb-4e67-8a54-bc942658a722
            resourceGroupName: gygax-tech-dns
            hostedZoneName: gygax.cloud
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gygax-cloud-wildcard-cert-data-azure
  namespace: traefik
spec:
  secretName: gygax-cloud-wildcard-cert-data-azure
  dnsNames:
    - "*.gygax.cloud"
  issuerRef:
    name: azuredns
    kind: Issuer
