---
additionalArguments:
  # - --entrypoints.websecure.http.tls.certresolver=cloudflare
  # - --entrypoints.websecure.http.tls.domains[0].main=example.com
  # - --entrypoints.websecure.http.tls.domains[0].sans=*.example.com
  # - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  # - --certificatesresolvers.cloudflare.acme.email=mail@example.com
  # - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  # - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json

ports:
  web:
    port: 80
    containerPort: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    redirectTo:
      port: websecure

  websecure:
    port: 443
    containerPort: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: gygax-cloud-wildcard-cert-data

service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.1.51
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: api-token
        name: cloudflare-api-credentials

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  name: traefik-data
  existingClaim: traefik-pvc
  path: /certs
  size: 128Mi
