#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100

service:
  main:
    enabled: true
    type: LoadBalancer

  ports:
    http:
      enabled: true
      port: 80
      targetPort: 80
      protocol: HTTP

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: WebSocket
    transport:
      respondingTimeouts:
        readTimeout: 300s
        writeTimeout: 300s
        idleTimeout: 300s
    labels: {}
    ingressClassName: traefik # "nginx"
    hosts:
      - host: audiobookshelf.gygax.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              name: audiobookshelf
              port: 80

persistence:
  metadata:
    enabled: true
    type: pvc
    mountPath: /metadata # /config
    readOnly: false
    nameOverride: metadata
    storageClass: longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 5Gi
    retain: true

  data:
    enabled: true
    type: pvc
    mountPath: /data # /config
    readOnly: false
    nameOverride: data
    storageClass: # "-"
    existingClaim: media-pvc # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 5Ti
    retain: true

  config:
    enabled: true
    type: pvc
    mountPath: /config # /config
    readOnly: false
    nameOverride: config
    storageClass: longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true

metrics:
  enabled: false
  serviceMonitor:
    interval: 3m
    scrapeTimeout: 1m
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []
  exporter:
    image:
      repository: ghcr.io/onedr0p/exportarr
      tag: v1.3.1
      pullPolicy: IfNotPresent
    env:
      port: 9793
      additionalMetrics: false
      unknownQueueItems: false
