
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

# when used with gluetun, a secret containing the WG_PRIVATE_KEY must be
# created before installing this chart

# kubectl create secret generic wg-private-key \
#     --from-literal=wg-private-key='<api-token>' \
#     --namespace mediacenter \
#     --type opaque

# helm install sabnzb bjw-s/app-template -f /sabnzb-gluetun/values.yaml


serviceAccount:
  create: false
# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      # Configure the main application container
      main:
        image:
          # -- image repository
          repository: lscr.io/linuxserver/sabnzbd
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: latest
        # Configure the container-specific securityContext
        securityContext:
          runAsUser: 1030
          runAsGroup: 100

      # Configure the gluetun sidecar
      # gluetun:
      #   dependsOn: main
      #   image:
      #     # -- image repository
      #     repository: qmcgaw/gluetun
      #     # -- image tag
      #     # this example is not automatically updated, so be sure to use the latest image
      #     tag: latest
      #   # -- environment variables.
      #   # See [image docs](https://github.com/qdm12/gluetun-wiki) for more details on how to configure
      #   # your VPN and how to set up port-forwarding.
      #   env:
      #     VPN_TYPE: wireguard
      #     VPN_INTERFACE: wg0
      #     VPN_SERVICE_PROVIDER: nordvpn
      #     WIREGUARD_PRIVATE_KEY: 
      #       valueFrom:
      #         secretKeyRef:
      #           name: wg-private-key
      #           key: wg-private-key
      #     WIREGUARD_ADDRESSES: 10.5.0.2/32
      #     SERVER_COUNTRIES: Switzerland
      #     FIREWALL_VPN_INPUT_PORTS: 563,53,853
      #     DNS_PLAINTEXT_ADDRESS: 1.1.1.1
      #   # Configure the container-specific securityContext
      #   securityContext:
      #     capabilities:
      #       add:
      #         - NET_ADMIN
    
service:
  # Configure a service for the main application
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8080

ingress:
  # Configure an Ingress for the main application
  main:
    className: "traefik"
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "sabnzb.gygax.cloud"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  # Configure the main configuration storage location
  config2:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      main:
        main:
          - path: /config

  config:
    existingClaim: media-pvc
    advancedMounts:
      main:
        main:
          - path: /data