---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

# Create a secret containing the PG user password before installing this chart
# kubectl create secret generic mealie-pg-pw \
#     --from-literal=mealie-pg-pw='<PG user password>' \
#     --namespace mediacenter \
#     --type opaque

# helm install mealie bjw-s/app-template -f /mealie/values.yaml

# serviceAccount:
#   create: false
# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        image:
          repository: ghcr.io/mealie-recipes/mealie
          tag: latest
        # Configure the container-specific securityContext
        securityContext:
          runAsUser: 1030
          runAsGroup: 100
        env:
          # Set Backend ENV Variables Here
          ALLOW_SIGNUP: "false"
          TZ: Europe/Zurich
          BASE_URL: https://mealie.gygax.cloud
          # DB_ENGINE: sqlite
          # Database Settings
          POSTGRES_DB: mealie
          DB_ENGINE: postgres
          POSTGRES_PORT: "5432"
          POSTGRES_USER: mealie
          POSTGRES_PASSWORD:
            secretKeyRef:
              name: mealie-pg-pw
              key: mealie-pg-pw
          POSTGRES_SERVER: 172.18.1.22

service:
  # Configure a service for the main application
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 9000

ingress:
  # Configure an Ingress for the main application
  main:
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "mealie.gygax.cloud"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  # Configure the main configuration storage location
  data:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
    advancedMounts:
      main:
        main:
          - path: /app/data
  nltk:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
    advancedMounts:
      main:
        main:
          - path: /nltk_data
