---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mediacenter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pvc
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k3s/mediacenter
    server: 10.125.0.24
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  storageClassName: ""
# Persistent Volume spec including capacity, access modes, NFS path, and server details follow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: media-pvc
  storageClassName: ""
# Persistent Volume Claim spec including access modes, resources requests, and storage class name follow
