---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mediacenter-nsfw
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nsfw-pvc
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k3s/nsfw
    server: 10.125.0.24
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  storageClassName: ""
# Persistent Volume spec including capacity, access modes, NFS path, and server details follow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nsfw-pvc
  namespace: mediacenter-nsfw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: nsfw-pvc
  storageClassName: ""
# Persistent Volume Claim spec including access modes, resources requests, and storage class name follow
