---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k3s/mediacenter/backup
    server: 10.125.0.24
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  storageClassName: ""
# Persistent Volume spec including capacity, access modes, NFS path, and server details follow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-backup-pvc
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: media-backup-pv
  storageClassName: ""
# Persistent Volume Claim spec including access modes, resources requests, and storage class name follow
