apiVersion: v1
kind: Service
metadata:
  name: rancher-lb
  labels:
    app: rancher
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.1.50
    app: rancher
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
  - port: 443
    targetPort: 443
  type: LoadBalancer
